services:
  # Rails Web Service (from Docker)
  - type: web
    name: smipe-web
    plan: free
    runtime: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /up
    preDeployCommand: "bundle exec rails db:prepare"
    disks:
      - name: smipe-sqlite-disk
        mountPath: /app/storage
        sizeGB: 1
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: SPOTIFY_CLIENT_ID
        sync: false
      - key: SPOTIFY_CLIENT_SECRET
        sync: false
    autoDeploy: true

  # PostgreSQL Database
  - type: pserv
    name: smipe-db
    plan: free
    postgresMajorVersion: "14"
    ipAllowList: [] # Allow all services in the account to connect 